name: Viewer Build and Deploy.

on:
  push:
    branches: [layout]
  pull_request:
    branches: [layout]

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nerfstudio/viewer/app
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
          cache: 'yarn'
          cache-dependency-path: ./nerfstudio/viewer/app/yarn.lock

      - name: Install packages
        run: yarn install

      - name: Build project
        run: CI=false yarn build

      - name: Move build files to workspace
        run: |
          mv ./nerfstudio/viewer/app/build/* $GITHUB_WORKSPACE

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./
