name: Viewer Build and Deploy.

on:
  push:
    branches: [layout]
  pull_request:
    branches: [layout]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nerfstudio/viewer_legacy/app
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
          cache: 'yarn'
          cache-dependency-path: ./nerfstudio/viewer_legacy/app/yarn.lock

      - name: Install packages
        run: yarn install

      - name: Build project
        run: CI=false yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./nerfstudio/viewer_legacy/app/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.12'

      - name: Install dependencies
        run: |
          pip install -r ./nerfstudio/viewer_legacy/app/requirements.txt

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./nerfstudio/viewer_legacy/app/build

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./nerfstudio/viewer_legacy/app/build
